export {default as NavBar} from './NavBar'
export {default as Hero} from './Hero'
export {default as About} from './About'
export {default as Info} from './Info'
export {default as WhatIDo} from './WhatIDo'
export {default as FeaturedWork} from './FeaturedWork'
export {default as MySkills} from './MySkills'