export {default as HomePage} from './HomePage'
export {default as AboutPage} from './AboutPage'
export {default as WorkPage} from './WorkPage'
export {default as ContactPage} from './ContactPage'
export {default as ProjectDetailPage} from './ProjectDetailPage'